# Figure sizes
SCALE = 1.5
# PRES_SCALE = 2
BASE_WIDTH = 5 # previously 10
BASE_HEIGHT = 4.3 # previously 9
# PRES_WIDTH = 5
# PRES_HEIGHT = 4.3

# Fontsizes
TITLE_FONTSIZE = 13
SUBTITLE_FONTSIZE = 11
LABEL_FONTSIZE = 9
TICK_FONTSIZE = 7

# Presentation fontsizes
PRES_TITLE_FONTSIZE = 14
PRES_SUBTITLE_FONTSIZE = 12
PRES_LABEL_FONTSIZE = 10
PRES_TICK_FONTSIZE = 8

# Position
TITLE_LOC = 1
TITLE_PAD = 10
CBAR_PAD = 0.05
LABEL_PAD = 10
CBAR_LABEL_PAD = 30